services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: passwordadmin
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  qdrant:
    image: qdrant/qdrant
    restart: always
    ports:
      - 6333:6333  # API port
      - 6334:6334  # Web UI port
    volumes:
      - qdrant_storage:/qdrant/storage
 
volumes:
  pgdata:
  qdrant_storage: